spring.application.name=hmg-test

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.url=jdbc:postgresql://10.126.111.172:5432/test
spring.datasource.username=test
spring.datasource.password=itcen789

spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.hibernate.ddl-auto=validate


# 바인딩 데이터 출력 옵션
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# 자바, JSP 리로드
spring.servlet.jsp.init-parameters.development=true

mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

logging.level.root=info
logging.level.com.hmg.as.test.hmg_test.mapper=debug
logging.level.org.mybatis=debug
logging.level.org.mybatis.spring=debug
logging.level.java.sql=debug
logging.level.jdbc.sqlonly=debug