spring.application.name=hmg-test

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.url=jdbc:postgresql://10.126.111.172:5432/test
spring.datasource.username=test
spring.datasource.password=itcen789

spring.jpa.properties.hibernate.format_sql=true

# 바인딩된 파라미터 값까지 출력
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE