spring.application.name=hmg-test

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.url=jdbc:postgresql://10.126.111.172:5432/test
spring.datasource.username=test
spring.datasource.password=itcen789